/**
 * Render a built template report to Markdown / structured JSON (issue #47).
 * PDF reuses renderCasePdf after filtering via buildCaseReportForTemplate.
 */

import { renderCaseMarkdown, renderTlpBanner, type CaseReportData } from "@/lib/report";
import { renderCasePdf } from "@/lib/report-pdf";
import type { BuiltReport } from "./build";
import type { ReportStamp, ReportSectionKey } from "./types";

function sectionEnabled(keys: Set<ReportSectionKey>, key: ReportSectionKey): boolean {
  return keys.has(key);
}

/**
 * Extend the base Markdown with template-only sections (evidence inventory,
 * related cases, custom fields, post-incident review) and a generation stamp.
 */
export function renderTemplatedMarkdown(
  built: BuiltReport,
  stamp: ReportStamp,
): string {
  const keys = new Set(built.includedKeys);
  // Base markdown already covers most sections when data is filtered.
  let md = renderCaseMarkdown(built.data);

  // When summary was excluded, strip the summary that renderCaseMarkdown
  // would only emit if present — already handled by nulling summary.
  // Append template-only sections not covered by the base renderer.
  const extra: string[] = [];

  if (sectionEnabled(keys, "custom_fields") && built.customFields.length > 0) {
    extra.push("## Custom fields", "");
    for (const f of built.customFields) {
      extra.push(
        `- **${f.label}** (\`${f.key}\`): ${
          f.value == null ? "—" : typeof f.value === "string" ? f.value : JSON.stringify(f.value)
        }`,
      );
    }
    extra.push("");
  }

  if (sectionEnabled(keys, "evidence_inventory") && built.evidenceInventory.length > 0) {
    extra.push("## Evidence inventory", "");
    for (const e of built.evidenceInventory) {
      extra.push(
        `- \`${e.filename}\` — ${e.status}, ${e.sizeBytes} bytes, sha256:${e.sha256 ?? "n/a"}${
          e.relevance ? `, relevance:${e.relevance}` : ""
        }`,
      );
    }
    extra.push("");
  }

  if (sectionEnabled(keys, "related_cases") && built.relatedCases.length > 0) {
    extra.push("## Related cases", "");
    for (const r of built.relatedCases) {
      extra.push(`- ${r.caseNumber} — ${r.title} (${r.relationshipType})`);
    }
    extra.push("");
  }

  if (sectionEnabled(keys, "post_incident_review")) {
    const c = built.data.case;
    if (c.rootCause || c.businessImpact || c.lessonsLearned || c.closureSummary) {
      // Base renderer already emits closure block for closed cases; ensure
      // post-incident fields appear even when still open.
      if (!(c.status === "closed" || c.closureReason)) {
        extra.push("## Post-incident review", "");
        if (c.closureSummary) extra.push(c.closureSummary, "");
        if (c.rootCause) extra.push(`**Root cause:** ${c.rootCause}`, "");
        if (c.businessImpact) extra.push(`**Business impact:** ${c.businessImpact}`, "");
        if (c.lessonsLearned) extra.push(`**Lessons learned:** ${c.lessonsLearned}`, "");
      }
    }
  }

  if (extra.length > 0) {
    md = `${md.trimEnd()}\n\n${extra.join("\n")}`;
  }

  const stampBlock = [
    "",
    "---",
    "",
    "## Export stamp",
    "",
    `- Case: **${stamp.caseNumber}**`,
    `- Generated: ${stamp.generatedAt}`,
    `- Template: ${stamp.templateName ?? "n/a"} v${stamp.templateVersion} (${stamp.variant})`,
    `- Format: ${stamp.format}`,
    `- Audience ceiling: TLP:${stamp.maxTlp.replace("_", "+")} / PAP:${stamp.maxPap}`,
    `- Content fingerprint: \`${stamp.contentFingerprint}\``,
    `- Data revision: \`${stamp.dataRevision}\``,
    stamp.sha256 ? `- SHA-256: \`${stamp.sha256}\`` : null,
    stamp.generatedByUserId ? `- Generated by: ${stamp.generatedByUserId}` : null,
  ]
    .filter(Boolean)
    .join("\n");

  return `${md.trimEnd()}\n${stampBlock}\n`;
}

export function renderTemplatedJson(
  built: BuiltReport,
  stamp: ReportStamp,
): string {
  const keys = new Set(built.includedKeys);
  const banner = renderTlpBanner(built.data.case.tlp);
  const body = {
    stamp: {
      ...stamp,
      tlpBanner: banner,
    },
    sections: built.selected,
    redaction: {
      maxTlp: built.redaction.maxTlp,
      maxPap: built.redaction.maxPap,
      includedCount: built.redaction.includedCount,
      excludedCount: built.redaction.excludedCount,
      maskedCount: built.redaction.maskedCount,
      // Items only — labels already safe for excluded/masked.
      items: built.redaction.items,
    },
    case: {
      id: built.data.case.id,
      caseNumber: built.data.case.caseNumber,
      title: built.data.case.title,
      status: built.data.case.status,
      severity: built.data.case.severity,
      tlp: built.data.case.tlp,
      pap: built.data.case.pap,
      classification: built.data.case.classification,
      summary: keys.has("summary") ? built.data.case.summary : null,
      tags: built.data.case.tags,
      dataClassificationTags: built.data.case.dataClassificationTags,
      openedAt: built.data.case.openedAt.toISOString(),
      closedAt: built.data.case.closedAt?.toISOString() ?? null,
      closureReason: keys.has("closure") ? built.data.case.closureReason : null,
      closureDetermination: keys.has("closure")
        ? built.data.case.closureDetermination
        : null,
      closureSummary:
        keys.has("closure") || keys.has("post_incident_review")
          ? built.data.case.closureSummary
          : null,
      rootCause: keys.has("post_incident_review") ? built.data.case.rootCause : null,
      businessImpact: keys.has("post_incident_review")
        ? built.data.case.businessImpact
        : null,
      lessonsLearned: keys.has("post_incident_review")
        ? built.data.case.lessonsLearned
        : null,
    },
    assignee: keys.has("metadata") ? built.data.assignee : null,
    reporter: keys.has("metadata") ? built.data.reporter : null,
    observables: keys.has("observables") ? built.data.observables : [],
    tasks: keys.has("tasks") ? built.data.tasks : [],
    timeline: keys.has("timeline")
      ? built.data.timeline.map((e) => ({
          eventType: e.eventType,
          payload: e.payload,
          occurredAt: e.occurredAt.toISOString(),
          actorName: e.actorName,
        }))
      : [],
    comments: keys.has("comments")
      ? built.data.comments.map((c) => ({
          id: c.id,
          body: c.body,
          createdAt: c.createdAt.toISOString(),
          authorName: c.authorName,
        }))
      : [],
    attackMappings: keys.has("ttp_mappings") ? built.data.attackMappings : [],
    attackStory: keys.has("attack_story") ? built.data.attackStory : [],
    contentBlocks: keys.has("investigation_blocks")
      ? built.data.contentBlocks.map((b) => ({
          id: b.id,
          type: b.type,
          title: b.title,
          content: b.content,
          tlp: b.tlp,
          pap: b.pap,
          revisionNumber: b.revisionNumber,
        }))
      : [],
    evidenceInventory: keys.has("evidence_inventory") ? built.evidenceInventory : [],
    relatedCases: keys.has("related_cases") ? built.relatedCases : [],
    customFields: keys.has("custom_fields") ? built.customFields : [],
  };
  return `${JSON.stringify(body, null, 2)}\n`;
}

export async function renderTemplatedPdf(
  data: CaseReportData,
): Promise<Buffer> {
  return renderCasePdf(data);
}
